apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana-operator-config

labels:
  - pairs:
      app: grafana-operator
      managedBy: argocd
      managementCodeGroup: chrismlee42-dev
      managementCodeProject: grafana-operator-config

# namespace: grafana-operator

patches:
  - patch: |-
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        annotations:
          argocd.argoproj.io/sync-options: Replace=true
        name: grafanas.grafana.integreatly.org

resources:
  # Determine latest stable version from https://github.com/grafana/grafana-operator/releases
  # - https://github.com/grafana/grafana-operator/releases/download/v5.19.4/crds.yaml
  - https://github.com/grafana/grafana-operator/releases/download/v5.19.4/kustomize-cluster_scoped.yaml
  - namespace.yaml
